kind: Service
apiVersion: v1
metadata:
  name: app1-internal
  annotations:
    cloud.google.com/load-balancer-type: "Internal"
spec:
  selector:
    app: app1
  ports:
  - protocol: TCP
    port: 8888
    targetPort: 8888
  type: LoadBalancer
