apiVersion: apps/v1
kind: Deployment
metadata:
    name: app1
spec:
    selector:
        matchLabels:
            app: app1
    replicas: 1
    template:
        metadata:
            labels:
                app: app1
        spec:
            containers:
            -   name: app1
                image: gcr.io/kalschi-istio/demo-app1:istio-v1
                imagePullPolicy: Always
                ports:
                    -   name: ws
                        containerPort: 8888
                livenessProbe:
                    tcpSocket:
                        port: 8888
                    initialDelaySeconds: 30
                readinessProbe:
                    tcpSocket:
                        port: 8888
                    initialDelaySeconds: 30
                resources:
                    requests:
                        cpu: 20m
                        memory: 1G   
                