kind: Service
apiVersion: v1
metadata:
  name: app1
  annotations:
    # Use Network Endpoint Group so traffic directly laod balanced to pods
    cloud.google.com/neg: '{"ingress": true}'
    # beta.cloud.google.com/backend-config: '{"ports": {"9999":"mud-backendconfig"}}'
spec:
  selector:
    app: app1
  ports:
  - protocol: TCP
    port: 8888
    name: app1-port
    targetPort: 8888
  type: NodePort
