kind: Service
apiVersion: v1
metadata:
  name: app2
  annotations:
    # Use Network Endpoint Group so traffic directly laod balanced to pods
    # cloud.google.com/neg: '{"ingress": true}'
    # beta.cloud.google.com/backend-config: '{"ports": {"9999":"mud-backendconfig"}}'
spec:
  selector:
    app: app2
  ports:
  - protocol: TCP
    port: 9999
    name: app2-port
    targetPort: 9999
  type: NodePort
